version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: runteq_rqb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: runteq_rqb_db
    volumes:
      - mysql_data:/var/lib/mysql
      - bundle_data:/usr/local/bundle
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: runteq_rqb_back
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
volumes:
  mysql_data:
  bundle_data:
