FROM --platform=linux/amd64 ruby:3.2.3
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev libvips
RUN mkdir /app
WORKDIR /app
RUN gem install bundler
COPY . /app
