FROM --platform=linux/amd64 ruby:3.2.3
RUN apt-get update -qq && apt-get install -y build-essential libvips default-mysql-client

WORKDIR /app

COPY Gemfile Gemfile.lock /app/

RUN gem install bundler
RUN bundle install

COPY . /app